workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    mollie-OAS:
        inputs:
            - location: https://raw.githubusercontent.com/mollie/openapi-specs/main/routes-bundled.yaml
        registry:
            location: registry.speakeasyapi.dev/mollie-oom/mollie/mollie-oas
targets:
    mollie:
        target: python
        source: mollie-OAS
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/mollie-oom/mollie/mollie-oas-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
